name: Build Test and Publish Nightly Packages

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - nightly

jobs:

  build-centos-7:
    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: edgedb/edgedb-pkg/integration/linux/build/centos-7@master
      env:
        PKG_REVISION: "<current-date>"
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "centos"
        PKG_PLATFORM_VERSION: "7"
        EXTRA_OPTIMIZATIONS: "true"

    - uses: actions/upload-artifact@v2
      with:
        name: builds-centos-7
        path: artifacts/centos-7

  build-centos-8:
    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: edgedb/edgedb-pkg/integration/linux/build/centos-8@master
      env:
        PKG_REVISION: "<current-date>"
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "centos"
        PKG_PLATFORM_VERSION: "8"
        EXTRA_OPTIMIZATIONS: "true"

    - uses: actions/upload-artifact@v2
      with:
        name: builds-centos-8
        path: artifacts/centos-8



  test-centos-7:
    needs: [build-centos-7]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-centos-7
        path: artifacts/centos-7

#    - name: Test
#      uses: edgedb/edgedb-pkg/integration/linux/test/centos-7@master
#      env:
#        PKG_SUBDIST: "nightly"
#        PKG_PLATFORM: "centos"
#        PKG_PLATFORM_VERSION: "7"


  test-centos-8:
    needs: [build-centos-8]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-centos-8
        path: artifacts/centos-8

#    - name: Test
#      uses: edgedb/edgedb-pkg/integration/linux/test/centos-8@master
#      env:
#        PKG_SUBDIST: "nightly"
#        PKG_PLATFORM: "centos"
#        PKG_PLATFORM_VERSION: "8"




  publish-centos-7:
    needs: [test-centos-7]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-centos-7
        path: artifacts/centos-7

    - name: Describe
      id: describe
      uses: edgedb/edgedb-pkg/integration/actions/describe-artifact@master
      with:
        target: centos-7

    - name: Publish
      uses: edgedb/edgedb-pkg/integration/linux/upload/centos-7@master
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "centos"
        PKG_PLATFORM_VERSION: "7"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"

    - name: Test Published
      uses: edgedb/edgedb-pkg/integration/linux/testpublished/centos-7@master
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "centos"
        PKG_PLATFORM_VERSION: "7"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"

    

  publish-centos-8:
    needs: [test-centos-8]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: builds-centos-8
        path: artifacts/centos-8

    - name: Describe
      id: describe
      uses: edgedb/edgedb-pkg/integration/actions/describe-artifact@master
      with:
        target: centos-8

    - name: Publish
      uses: edgedb/edgedb-pkg/integration/linux/upload/centos-8@master
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "centos"
        PKG_PLATFORM_VERSION: "8"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"
        PACKAGE_UPLOAD_SSH_KEY: "${{ secrets.PACKAGE_UPLOAD_SSH_KEY }}"

    - name: Test Published
      uses: edgedb/edgedb-pkg/integration/linux/testpublished/centos-8@master
      env:
        PKG_SUBDIST: "nightly"
        PKG_PLATFORM: "centos"
        PKG_PLATFORM_VERSION: "8"
        PKG_VERSION_SLOT: "${{ steps.describe.outputs.version-slot }}"

    


